site_name: Starlette-Login
site_description: User session management for Starlette

theme:
  name: 'material'
#  custom_dir: docs/overrides
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

repo_name: jockerz/Starlette-Login
repo_url: https://github.com/jockerz/Starlette-Login
edit_uri: ""

nav:
  - Basic: index.md
  - Customization:
    - Login Manager: custom/login-manager.md
    - Configuration: custom/configuration.md
  - Advance Usage:
    - Custom Decorator: advance/decorators.md
  - Tutorial:
    - SQLAdmin: tutorial/sqladmin.md
  - Contribution: contribution.md
